### ISSUE TITLE
Japanese Pokemon Ruby and Sapphire are using the English box art instead of the Japanese ones

### ISSUE THREAD

**Issue by rcmp09** [codewario/PocketLibraryImages#17]
Japanese Pokemon Ruby and Sapphire are using the English box art instead of the Japanese ones

**Comment by codewario** [comment]
May be the same issue as #19, though these titles are not mentioned in that ticket.

**Comment by codewario** [comment]
[This appears to be the same problem](https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance/blob/17c74d9d2529bc79b7036417f3ee4794de964438/Named_Boxarts/Pocket%20Monsters%20-%20Sapphire%20(Japan).png) as the aforementioned issue, the incorrect artwork is specified for that region's revision(s) of the game. Unfortunately, the box arts will need to be addressed at the source, in libretro-thumbnails, for the same reasons mentioned there.
